"""Built-in resume styles."""

from __future__ import annotations

from md2resume.models import ResumeStyle

STYLES: dict[str, ResumeStyle] = {
    "classic_navy": ResumeStyle(
        id="classic_navy",
        label="Classic — Navy",
        description="Single column, name on top, simple rules (navy & gray)",
        layout="classic",
        primary="#1e3a5f",
        secondary="#334e68",
        accent="#475569",
        text="#1e293b",
        muted="#64748b",
        surface="#f8fafc",
        border="#cbd5e1",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="22pt",
        h2_size="11pt",
        h3_size="10.5pt",
        body_size="10pt",
        line_height="1.2",
        section_uppercase=True,
    ),
    "classic_charcoal": ResumeStyle(
        id="classic_charcoal",
        label="Classic — Charcoal",
        description="Traditional serif single column, charcoal & cool gray",
        layout="classic",
        primary="#1f2937",
        secondary="#374151",
        accent="#4b5563",
        text="#111827",
        muted="#6b7280",
        surface="#f9fafb",
        border="#d1d5db",
        heading_font="Georgia, 'Times New Roman', Times, serif",
        body_font="Georgia, 'Times New Roman', Times, serif",
        h1_size="23pt",
        h2_size="11pt",
        h3_size="10.5pt",
        body_size="10.5pt",
        line_height="1.25",
        section_uppercase=True,
    ),
    "split_steel": ResumeStyle(
        id="split_steel",
        label="Split header — Steel",
        description="Name left, contact right on one row; steel blue accents",
        layout="split_header",
        primary="#1e3a5f",
        secondary="#475569",
        accent="#64748b",
        text="#1e293b",
        muted="#64748b",
        surface="#f1f5f9",
        border="#cbd5e1",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="22pt",
        h2_size="11pt",
        h3_size="10.5pt",
        body_size="10pt",
        line_height="1.2",
        section_uppercase=True,
    ),
    "header_navy": ResumeStyle(
        id="header_navy",
        label="Top bar — Navy",
        description="Solid navy header band; contact inside the bar",
        layout="header_bar",
        primary="#172554",
        secondary="#1e3a5f",
        accent="#334155",
        text="#1e293b",
        muted="#64748b",
        surface="#f8fafc",
        border="#cbd5e1",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="21pt",
        h2_size="11pt",
        h3_size="10.5pt",
        body_size="10pt",
        line_height="1.2",
        section_uppercase=True,
    ),
    "sidebar_navy": ResumeStyle(
        id="sidebar_navy",
        label="Sidebar — Navy panel",
        description="Dark left column (contact, skills, education); experience on the right",
        layout="sidebar_left",
        primary="#0f172a",
        secondary="#1e293b",
        accent="#334155",
        text="#1e293b",
        muted="#64748b",
        surface="#f8fafc",
        border="#cbd5e1",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="16pt",
        h2_size="10pt",
        h3_size="10.5pt",
        body_size="9.5pt",
        line_height="1.22",
        section_uppercase=True,
    ),
    "sidebar_slate": ResumeStyle(
        id="sidebar_slate",
        label="Sidebar — Slate panel",
        description="Gray-blue sidebar; main column for summary and roles",
        layout="sidebar_left",
        primary="#1e293b",
        secondary="#334155",
        accent="#475569",
        text="#1e293b",
        muted="#64748b",
        surface="#f8fafc",
        border="#e2e8f0",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="16pt",
        h2_size="10pt",
        h3_size="10.5pt",
        body_size="9.5pt",
        line_height="1.22",
        section_uppercase=True,
    ),
    "timeline_slate": ResumeStyle(
        id="timeline_slate",
        label="Timeline — Slate",
        description="Experience entries with a left timeline rule; muted slate palette",
        layout="timeline",
        primary="#334155",
        secondary="#475569",
        accent="#64748b",
        text="#1e293b",
        muted="#64748b",
        surface="#f8fafc",
        border="#cbd5e1",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="21pt",
        h2_size="11pt",
        h3_size="10.5pt",
        body_size="10pt",
        line_height="1.2",
        section_uppercase=True,
    ),
    "minimal_gray": ResumeStyle(
        id="minimal_gray",
        label="Minimal — Gray",
        description="No panels or bars; thin rules and maximum whitespace",
        layout="minimal",
        primary="#374151",
        secondary="#4b5563",
        accent="#6b7280",
        text="#111827",
        muted="#6b7280",
        surface="#ffffff",
        border="#e5e7eb",
        heading_font="'Helvetica Neue', Helvetica, Arial, sans-serif",
        body_font="'Helvetica Neue', Helvetica, Arial, sans-serif",
        h1_size="20pt",
        h2_size="10pt",
        h3_size="10pt",
        body_size="9.5pt",
        line_height="1.3",
        section_uppercase=False,
    ),
    "enhancv_it": ResumeStyle(
        id="enhancv_it",
        label="Enhancv IT (examples/)",
        description="Two-column slate sidebar (#3c5769): photo & QR top-left, experience right",
        layout="enhancv_sidebar",
        primary="#3c5769",
        secondary="#2f4555",
        accent="#4a6a7f",
        text="#1e293b",
        muted="#64748b",
        surface="#f4f6f7",
        border="#c5d0d8",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="15pt",
        h2_size="10.5pt",
        h3_size="10pt",
        body_size="9.5pt",
        line_height="1.22",
        section_uppercase=True,
    ),
    "ats_section_rule": ResumeStyle(
        id="ats_section_rule",
        label="ATS section rules",
        description="Single column, heavy section underlines (web example style)",
        layout="ats_sections",
        primary="#000000",
        secondary="#374151",
        accent="#6b7280",
        text="#111827",
        muted="#6b7280",
        surface="#ffffff",
        border="#e5e7eb",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="22pt",
        h2_size="12pt",
        h3_size="10.5pt",
        body_size="10pt",
        line_height="1.25",
        section_uppercase=False,
    ),
    "photo_header_gray": ResumeStyle(
        id="photo_header_gray",
        label="Photo header",
        description="Photo & QR top-right; contact under name; body single column",
        layout="photo_header",
        primary="#1e293b",
        secondary="#475569",
        accent="#64748b",
        text="#1e293b",
        muted="#64748b",
        surface="#f8fafc",
        border="#cbd5e1",
        heading_font="'Segoe UI', Calibri, Arial, sans-serif",
        body_font="Calibri, 'Segoe UI', Arial, sans-serif",
        h1_size="22pt",
        h2_size="11pt",
        h3_size="10.5pt",
        body_size="10pt",
        line_height="1.2",
        section_uppercase=True,
    ),
}

LEGACY_STYLE_MAP: dict[str, str] = {
    "professional": "classic_navy",
    "classic": "classic_charcoal",
    "modern": "split_steel",
    "tech": "sidebar_slate",
    "ocean": "enhancv_it",
    "forest": "classic_charcoal",
    "sunset": "classic_navy",
    "violet": "minimal_gray",
    "midnight": "header_navy",
    "slate": "timeline_slate",
}



THEMES = STYLES


def resolve_style_id(style_id: str | None) -> str:
    if not style_id:
        return "classic_navy"
    return LEGACY_STYLE_MAP.get(style_id, style_id)
